import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RegisterContextProvider from "@/context/registerContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Super Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-full contain min-h-screen py-20 bg-cover bg-bg_svg bg-fixed `}
      >
        <RegisterContextProvider>{children}</RegisterContextProvider>
      </body>
    </html>
  );
}
